### ISSUE TITLE
Pagination seems to be broken (fix inside)

### ISSUE THREAD

**Issue by mobweb** [quafzi/magento-CustomerGridOrderCount#2]
I've created a fork of this project at https://github.com/mobweb/magento-CustomerGridOrderCount to cover a requirement for a current project of mine (displaying the order count not on the customer but the order grid).

I've noticed that installing this extension seems to break pagination. The reason seems to be a bug with the `$collection->groupByAttribute()` method: http://stackoverflow.com/questions/3485455/using-group-breaks-getselectcountsql-in-magento/4219386#4219386.

I've implemented the fix from the linked SO question by copying the `lib/Varien/Data/Collection/Db.php` file to the local code pool: https://github.com/mobweb/magento-CustomerGridOrderCount/commit/d5d90b77f910cc1bf45365b5279e761cb7784f8d. Is that something you'd want to implement in your extension? I can send you a pull request.

I've also noticed that sorting by the new `order_count` attribute seems to be broken (with or without the fix implemented above). But for this problem I was unable to find a solution. Any ideas why it doesn't work?

**Comment by quafzi** [comment]
Hi @mobweb, does the error still occur with the current version (0.2.7)?
