### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'customer_id' in group statement is ambiguous

### ISSUE THREAD

**Issue by theskillwithin** [quafzi/magento-CustomerGridOrderCount#4]
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'customer_id' in group statement is ambiguous

Trace:
#0 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Zend/Db/Statement.php(301): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#4 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Varien/Db/Adapter/Pdo/Mysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#5 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Zend/Db/Adapter/Abstract.php(825): Varien_Db_Adapter_Pdo_Mysql->query(Object(Varien_Db_Select), Array)
#6 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Varien/Data/Collection/Db.php(225): Zend_Db_Adapter_Abstract->fetchOne(Object(Varien_Db_Select), Array)
#7 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Varien/Data/Collection.php(225): Varien_Data_Collection_Db->getSize()
#8 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Varien/Data/Collection.php(211): Varien_Data_Collection->getLastPageNumber()
#9 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Varien/Data/Collection/Db.php(516): Varien_Data_Collection->getCurPage()
#10 /chroot/home/skincare/dev.skincarebyalana.com/html/lib/Varien/Data/Collection/Db.php(563): Varien_Data_Collection_Db->_renderLimit()
#11 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(533): Varien_Data_Collection_Db->load()
#12 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/local/Mage/Adminhtml/Block/Sales/Order/Grid.php(65): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()
#13 [internal function]: Mage_Adminhtml_Block_Sales_Order_Grid->_prepareCollection()
#14 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/community/Quafzi/CustomerGridOrderCount/Model/Observer.php(41): ReflectionMethod->invoke(Object(Mage_Adminhtml_Block_Sales_Order_Grid))
#15 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/community/Quafzi/CustomerGridOrderCount/Model/Observer.php(29): Quafzi_CustomerGridOrderCount_Model_Observer->_callProtectedMethod(Object(Mage_Adminhtml_Block_Sales_Order_Grid), '_prepareCollect...')
#16 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/community/Quafzi/CustomerGridOrderCount/Model/Observer.php(19): Quafzi_CustomerGridOrderCount_Model_Observer->_modifyGrid(Object(Mage_Adminhtml_Block_Sales_Order_Grid), 'created_at')
#17 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Model/App.php(1338): Quafzi_CustomerGridOrderCount_Model_Observer->beforeBlockToHtml(Object(Varien_Event_Observer))
#18 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Quafzi_CustomerGridOrderCount_Model_Observer), 'beforeBlockToHt...', Object(Varien_Event_Observer))
#19 /chroot/home/skincare/dev.skincarebyalana.com/html/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('core_layout_blo...', Array)
#20 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Model/Layout.php(459): Mage::dispatchEvent('core_layout_blo...', Array)
#21 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(66): Mage_Core_Model_Layout->createBlock('adminhtml/sales...', 'sales_order.gri...')
#22 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/local/Mage/Core/Block/Abstract.php(238): Mage_Adminhtml_Block_Widget_Grid_Container->_prepareLayout()
#23 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mybuys_Connector_Model_Layout))
#24 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/sales...', 'sales_order.gri...')
#25 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/sales...', 'sales_order.gri...')
#26 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/community/Mybuys/Connector/Model/Layout.php(54): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#27 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Model/Layout.php(205): Mybuys_Connector_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#28 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#29 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#30 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#31 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#32 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(59): Mage_Adminhtml_Controller_Action->loadLayout()
#33 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(94): Mage_Adminhtml_Sales_OrderController->_initAction()
#34 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Adminhtml_Sales_OrderController->indexAction()
#35 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#36 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#37 /chroot/home/skincare/dev.skincarebyalana.com/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#38 /chroot/home/skincare/dev.skincarebyalana.com/html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#39 /chroot/home/skincare/dev.skincarebyalana.com/html/index.php(96): Mage::run('', 'store')
#40 {main}

**Comment by theskillwithin** [comment]
Magento ver. 1.7.0.2

**Comment by quafzi** [comment]
Would be great to know, in which situation you got that error.

**Comment by quafzi** [comment]
@theskillwithin Did that solve your problem?

**Comment by theskillwithin** [comment]
Yes!  Thank you so much!!!
